### ISSUE TITLE
Basic auth support

### ISSUE THREAD

**Issue by bre7** [vapor/redis#100]
Is there a way to authenticate using user/password ? (For Heroku's Redis service)

**Comment by pedantix** [comment]
Yes! Sort of...I use redis labs, and in their connection string you get a password, iirc heroku does the same thing. No username because the redis protocol doesn’t account for it. I plan on doing a PR to document it better once my PR that switches RedisConfig to URL based connection strings goes through. RedisConfig, takes a password as an optional variable, currently.

**Comment by bre7** [comment]
Yeah, I did try using RedisConfig but wasn't working correctly. Will report back

**Comment by pedantix** [comment]
I'll look into this sorry.

**Comment by bre7** [comment]
Thanks. I’ll provide a sample project if you want (using free dynos)
