### ISSUE TITLE
Do all commands work ?

### ISSUE THREAD

**Issue by Herz3h** [vapor/redis#45]
I'm trying to set an hmap with this line : 

let message = try client!.command("HMSET", params: ["messages", "content", "blalba", "token", "123456"])
let writtenMessages = try client.command("HGET", params: ["messages", "content"])

But printing writtenMessages.toString() gives me the "OK" message instead of the content...

I have no idea how to do this, so is this supported, if so how do you do it ?

**Comment by johnbona** [comment]
You may be hitting the same issue that @IanKeen had in the Slack channel with #31. Redbird isn't thread safe but you can use [Lock](https://github.com/vapor/core/blob/master/Sources/Core/Lock.swift) in vapor/core to easily work around this.

Feel free to hit me up in the Slack channel if you have any problems!

**Comment by IanKeen** [comment]
Yeah locking appears to have resolved my issues, you can see my usage [here](https://github.com/ChameleonBot/Services/blob/master/Sources/Services/Storage/RedisStorage.swift). I had to modify `Lock` slightly to return any value rather than `Void` (see [here](https://github.com/ChameleonBot/Common/blob/master/Sources/Common/Lock.swift))

**Comment by tanner0101** [comment]
Closing this since locking / thread safety is out of the scope of this package. If you want to work on multiple threads, the easiest solution is to create a client for each thread.
